name: emoji_loading
description: "A new Flutter package project."
version: 1.0.0
homepage: https://github.com/VenuNeosoft/emogi_loading_package
repository: https://github.com/your_username/emoji_loading
issue_tracker: https://github.com/your_username/emoji_loading/issues

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
