name: emoji_loading
description: "A fun Flutter package that adds emoji-based or text-based loading animations like bounce, wave, pulse, and rotate to your app."

version: 1.0.2
homepage: https://github.com/VenuNeosoft/emogi_loading_package
repository: https://github.com/VenuNeosoft/emogi_loading_package
issue_tracker: https://github.com/VenuNeosoft/emogi_loading_package/issues

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
